spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: qwerboom
    driverClassName: com.mysql.cj.jdbc.Driver
    max-active: 200
    max-idle: 30
    min-idle: 10
    initial-size: 10
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect